# Generated by Django 6.0.7 on 2026-08-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
