# Generated by Django 6.0.7 on 2026-08-18 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_created_at_comment_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
